tracks/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),

    url(r'^users$', views.users_view, name='users_view'),
    url(r'^users/id(?P<user_id>[0-9]+)/$', views.user_info_view, name='user_info_view'),
    url(r'^api/tracks/start/id(?P<user_id>[0-9]+)$', views.user_start_tracking, name='user_start_tracking'),
    url(r'^api/tracks/stop/id(?P<user_id>[0-9]+)$', views.user_stop_tracking, name='user_stop_tracking'),
    url(r'^secret_form/id(?P<user_id>[0-9]+)$', views.secret_form, name='secret_form'),
    url(r'^users/add$', views.user_start_tracking_by_page_address, name='user_add_by_address'),
    url(r'^api/tracks/id(?P<user_id>[0-9]+)$', views.user_track_json, name='user_track_json'),

]

tracks/models.py
from django.db import models


class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    has_mobile = models.BooleanField()
    uid = models.IntegerField()
    last_update = models.DateTimeField()
    secret = models.CharField(default="00000000000000000000000000000000", max_length=32)
    tracking = models.BooleanField(default=True)

    def __unicode__(self):
        return str(self.uid)


class Timestamp(models.Model):
    PLATFORMS = ((1, "mobile version"),
                 (2, "iphone app"),
                 (3, "ipad app"),
                 (4, "android app"),
                 (5, "winphone app"),
                 (6, "win8 app"),
                 (7, "full version"))

    last_seen_time = models.DateTimeField()
    last_seen_platform = models.IntegerField(choices=PLATFORMS)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    online = models.BooleanField()
    online_mobile = models.BooleanField(default=False)
    created_at = models.DateTimeField(null=True)

    def __unicode__(self):
        return str(self.created_at) + " - " + str(self.user.uid)

tracks/views.py
import json
from django.http import HttpResponse
from .models import Timestamp, User
from django.shortcuts import render
from vk_api_helper import query_users, get_photo
from datetime import datetime
from uuid import uuid4
from urlparse import urlparse


def user_track_json(request, user_id):
    user = User.objects.filter(uid=user_id)
    if user:
        user = user.get()
        track = [
            {'last_seen_time': ts.last_seen_time.isoformat(),
                'last_seen_platform': ts.last_seen_platform,
                'online': ts.online,
                'online_mobile': ts.online_mobile,
                'created_at': ts.created_at.isoformat()} for ts
            in Timestamp.objects.filter(user=user).order_by("created_at")
            ]

        track_changes = 0
        online_count = sum((1 for t in track if t['online']))
        mobile_count = sum(1 for t in track if t['online_mobile'])
        platform_stats = [{Timestamp.PLATFORMS[i-1][1]:
                               sum(1 for t in track if t['last_seen_platform'] == i)}
                          for i in range(1, 8)] # platform name : number of total visits tracked

        return HttpResponse(json.dumps({'result': True,
                                        'track': track,
                                        'count': len(track),
                                        'online_count': online_count,
                                        'mobile_count': mobile_count,
                                        'platform_stats': platform_stats,
                                        'track_changes': track_changes}),
                            content_type='application/json')

    else:
        return HttpResponse(json.dumps({'result': False, 'message': 'User not found.', 'track': None}),
                            content_type='application/json')


def user_start_tracking_by_page_address(request):
    link = request.POST.get("link")
    id_or_screenname = urlparse(link).path.strip('/')
    if id_or_screenname:
        from vk.exceptions import VkAPIError
        try:
            vk_query = query_users(id_or_screenname)
            uid = vk_query[0]["uid"]
            return user_start_tracking(request, uid)
        except VkAPIError as e:
            return users_view(request)
    else:
        return users_view(request)


def user_start_tracking(request, user_id):
    try:
        vk_user = query_users(user_id)[0]
        if not User.objects.filter(uid=vk_user["uid"]):
            secret = uuid4().get_hex()
            u = User(
                first_name=vk_user["first_name"],
                last_name=vk_user["last_name"],
                has_mobile=vk_user["has_mobile"],
                uid=vk_user["uid"],
                last_update=datetime.now(),
                secret=secret
            )
            u.save()

            return HttpResponse(json.dumps(
                {'result': True, 'secret': secret}),
                content_type='application/json')
        else:
            return HttpResponse(json.dumps(
                {'result': False, 'message': "This user is already tracked."}),
                content_type='application/json')
    except Exception as e:
        return HttpResponse(json.dumps({'result': False, 'message': e.message, 'response': vk_user}),
                            content_type='application/json')


def user_stop_tracking(request, user_id):
    user = User.objects.filter(uid=user_id)
    if user:
        user = user.get()
        secret = request.POST.get('secret')
        if secret == user.secret:
            user.tracking = False
            user.save()
            return render(request, "tracks/stop_result.html", {'result': True, 'user': user})
        else:
            print 'user secret: ', user.secret, '; you entered: ', request.POST.get('secret')
            return render(request, "tracks/stop_result.html", {'result': False, 'message': 'Invalid secret.'})
    else:
        return render(request, "tracks/stop_result.html", {'result': False, 'message': 'User is not found.'})


def secret_form(request, user_id):
    user = User.objects.filter(uid=user_id)
    if user:
        user = user.get()
        context = {'user': user}
        return render(request, "tracks/secret_form.html", context)
    else:
        return render(request, "tracks/secret_form.html")


def user_info_view(request, user_id):
    """should include track info. like it's advanced view with every piece of info included"""
    user = User.objects.filter(uid=user_id)
    if user:
        user = user.get()
        track = Timestamp.objects.filter(user=user).order_by("-created_at")
        context = {'user': user, 'track': track, "given_uid": user_id, 'photo': get_photo(user.uid)[0].get("photo_medium"),
                   'track_started': track.last().created_at}
        return render(request, "tracks/user_info.html", context)
    else:
        context = {'user': None, 'track': None, 'given_uid': user_id}
        return render(request, "tracks/user_info.html", context)


def users_view(request):
    users = list(User.objects.all())
    context = {'users': users}
    return render(request, "tracks/users.html", context)


def index(request):
    return users_view(request)

tracks/templates/tracks/secret_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vk Spy - Stop tracking</title>
</head>
<body>
    {% if user %}
        <h3>If you really want to stop tracking {{ user.first_name }} {{ user.last_name }}, enter your secret in the form below</h3>

        <form method="post" action={% url "user_stop_tracking" user.uid%}>
        {% csrf_token %}
            <input name="secret" type="text">
            <input type="submit" value="Stop tracking">
        </form>

    {% else %}
        <h3>You can't stop tracking without specifying the id.</h3>
    {% endif %}
</body>
</html>

tracks/templates/tracks/stop_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stop tracking</title>
</head>
<body>
    {% if result %}
    <h3>Stopping successful. {{ user.first_name }} {{ user.last_name }} is no longer under surveillance.</h3>
    {% else %}
    <h3>{{ message }}</h3>
    {% endif %}
    <br>
    <a href={% url "users_view" %}>Back to users list</a>
</body>
</html>

tracks/templates/tracks/user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User info - {{ user.first_name }} {{ user.last_name }}</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
</head>
<body style="padding-left: 20px; padding-right: 20px">
    {% if user %}
        {% if photo %}
            <div id="user-info-holder" style="overflow: hidden;">
        <div id="user-photo" style="float:left; padding-right: 10px; padding-top: 30px;">
            <img src={{ photo }} style="border-radius: 50%;"/>
        </div>
        {% endif %}
        <div id="user-info" style="float:left">
        <h3>User info - <a href="http://vk.com/id{{ user.uid }}" target="_blank">id{{ user.uid }}</a></h3>
        <ul>
            <li>{{ user.first_name }} {{ user.last_name }}</li>
            <li>Has mobile: {% if user.has_mobile %} Yes {% else %} No {% endif %}</li>
            <li>Track started: {{ track_started }}</li>
            <li>Last update: {{ user.last_update }}</li>
        </ul>
    </div>
        </div>
    {% if track %}

        <div class="container">
        <ul class="nav nav-tabs nav-justified">
            <li class="active"><a data-toggle="tab" href="#track-info-timeline">Timeline</a></li>
            <li><a data-toggle="tab" href="#track-info-table">Table</a></li>
            <li><a data-toggle="tab" href="#track-stats">Stats</a></li>
        </ul>
            <div class="tab-content" style="padding-top: 20px">

            <div id="track-info-timeline" class="tab-pane fade in active">
            <canvas id="timeline" width='100%' height='30'></canvas>
        </div>

        <div id="track-info-table" class="tab-pane fade">

        <table class="table table-striped table-bordered">
            <caption><h3>Track</h3></caption>
            <thead>
            <tr><th>Time</th>
                <th>Online</th>
            <th>Last seen</th>
            <th>Platform</th></tr>
            </thead>
            <tbody>
                {% for entry in track %}
                    <tr>
                        <td> {{ entry.created_at }} </td>
                        <td> {{ entry.online }} </td>
                        <td> {{ entry.last_seen_time }} </td>
                        <td> {{ entry.get_last_seen_platform_display }} </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
        <div id="track-stats" class="tab-pane fade" style="overflow: hidden">
            <div style="float: left; width: 50%">
                <canvas id="mobile-piechart"></canvas>
            </div>
            <div style="float: left; width: 50%">
                <canvas id="online-piechart"></canvas>
            </div>
        </div>
        </div>
    </div>
    {% else %}
        <h4>Track collection is in progress, check later.</h4>
    {% endif %}

    {% else %}
        <p>User is not found. <a href={% url "user_start_tracking" given_uid %}>Start tracking</a>?
    {% endif %}

    <script>
        function drawTimeline(data) {
                var ctx = document.getElementById("timeline");
                // console.log(data);
                var timeline = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: data.track.map(function (x,index) {

                                return moment(x.created_at).format("MM/DD/YYYY HH:mm");

                        }),
                        datasets: [{
                            label: 'uptime',
                            data: data.track.map(function (x) {
                                return x.online ? 1 : 0
                            }),
                            backgroundColor: [
                                '#D1D9E0'
                            ],
                            borderColor: [
                                '#507299'
                            ],
                            borderWidth: 1,
                            steppedLine: true,
                        }],
                    },
                    options: {
                        legend: {
                            display: false
                        },
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true,
                                    callback: function (value, index, values) {
                                        if (value == 0) {
                                            return "Offline";
                                        }
                                        if (value == 1) {
                                            return "Online";
                                        }
                                    },
                                }
                            }],
                            xAxes: [{
                               type: "time",
                                time: {
                                    minUnit: "second",
                                    format: 'MM/DD/YYYY HH:mm'

                                }
                            }]
                        },
                    }
                });
            };

        function drawOnlinePieChart(serverData){
            var ctx = document.getElementById("online-piechart");
            var data = {
                labels: serverData.platform_stats.map(function(x){return Object.keys(x)[0]}),
                datasets: [
                    {
                        data: serverData.platform_stats.map(
                        function(a){var k = Object.keys(a)[0]; return a[k]}),
                        backgroundColor: [
                            "#FF6384",
                            "#36A2EB",
                            "#FFCE56",
                            "#84A1D1",
                            "#7A9A37",
                            "#634786",
                            "#326AAC"
                        ],
                        hoverBackgroundColor: [
                            "#FF6384",
                            "#36A2EB",
                            "#FFCE56",
                            "#84A1D1",
                            "#7A9A37",
                            "#634786",
                            "#326AAC"
                        ]
                    }]
            };
            var myDoughnutChart = new Chart(ctx, {
                type: 'doughnut',
                data: data,
                options: {
                    title:{
                        display: false,
                        text: "Devices"
                    },
                    legend: {
                        position: "right"
                    }
                }
            });
        }

        function drawMobilePiechart(serverData){
            var ctx = document.getElementById("mobile-piechart");
            var data = {
                labels: ["Mobile device","Desktop"],
                datasets: [
                    {
                        data: [serverData.mobile_count,
                            serverData.online_count - serverData.mobile_count],
                        backgroundColor: [
                            "#36A2EB",
                            "#326AAC"
                        ],
                        hoverBackgroundColor: [
                            "#36A2EB",
                            "#326AAC"
                        ]
                    }]
            };
            var myDoughnutChart = new Chart(ctx, {
                type: 'doughnut',
                data: data,
                options: {
                    legend: {
                        position: "left"
                    }
                }
            });
        }

        $(document).ready(function() {

            // getting track from api

            $.getJSON("{%  url 'user_track_json' user.uid %}",
                    function(data){
                        drawTimeline(data);
                        drawOnlinePieChart(data);
                        drawMobilePiechart(data);
                    }
            );
            // rendering DT

            $('#users-table').DataTable(
            {
                "paging": false
            }
            );

            // remembering tab after page refresh
            var active = localStorage.getItem("activeTab");
            $("a[href='"+active+"']").tab("show");
    });

        // storing current tab to remember it later
        window.onbeforeunload = function () {
          var active = $("li.active>a").attr("href");
            localStorage.setItem("activeTab", active);
        };
    </script>
</body>
</html>

tracks/templates/tracks/users.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>VkSpy - Tracked users list</title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body style="padding-left: 20px; padding-right: 20px">
<div name="add-user">
    <h3>Add new user</h3>
    <form method="post" action={% url "user_add_by_address"%}>
        {% csrf_token %}
        <input name="link" type="url">
        <input type="submit" value="Add">
    </form>
    <br><hr>
</div>

<table id="users-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <caption><h3>Tracked users list (total:{{ users|length }})<h3></caption>
        <thead>
        <tr>
            <th>UID</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Has mobile?</th>
            <th>Last Update</th>
            <th>Tracking</th>
            <th> </th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td><a href={% url 'user_info_view' user.uid %}>{{ user.uid }}</a></td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.has_mobile }}</td>
                <td>{{ user.last_update }}</td>
                <td>{{ user.tracking }}</td>
                <td>
                    {% if user.tracking %}
                    <a href={% url 'secret_form' user %}>stop tracking</a>
                    {% endif %}
                </td>
            </tr>

        {% endfor %}
    </tbody>
    </table>
<script lang="js">
    $(document).ready(function() {
    $('#users-table').DataTable(
            {
                "lengthMenu": [[-1, 100, 50, 20, 10], ["All", 100, 50, 20, 10]]
            }
    );
    });
</script>
</body>
</html>